# Generated by Django 4.0.2 on 2022-08-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descriptions',
            field=models.TextField(verbose_name='descriptions'),
        ),
    ]
