# Generated by Django 4.0.2 on 2022-08-29 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('is_question', models.BooleanField(default=False, verbose_name='question')),
                ('is_reply', models.BooleanField(default=False, verbose_name='reply')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='ContactUs.contactus', verbose_name='parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'contact us',
            },
        ),
    ]
